### ISSUE TITLE
scroll-view bug 滚动问题，写死的代码可以正常响应，动态传入的代码无法响应

### ISSUE THREAD

**Issue by macmatilda** [newteo/team-blog-repo#108]
（1）无法自动关东
`
<scroll-view scroll-y style="height: 250px;" scroll-into-view="a3">
        <block wx:for="{{messageList}}" wx:key="id">
            <view id="{{item.id}}" style="background-color: green; height: 200px; width:100%;"> {{item.id}}</view>
        </block>
    </scroll-view>
`
// this.setData({messageList: [{id: 'a1'}, {id: 'a2'}, {id: 'a3'}, {id: 'a4'}]});
通过setData 滚动条无法滚动到a3

（2)如果代码写死，是可以滚动的

`
<scroll-view scroll-y style="height: 250px;" scroll-into-view="a3">
        
        <block wx:for="{{[{id:'a1'},{id:'a2'}, {id:'a3'}, {id:'a4'}]}}" wx:key="id">
            <view id="{{item.id}}" style="background-color: green; height: 200px; width:100%;"> {{item.id}}</view>
        </block>
    </scroll-view>
`

**Comment by joephon** [comment]
and?
